import type { AnalysisResult } from "./types";

export const DEMO_ANALYSIS: AnalysisResult = {
  mode: "demo",
  providerLabel: "Demo mapping",
  pages: 4,
  matchedAnswers: 12,
  confidence: 96,
  note: "A sample result is shown when no AI key is available. Upload your own files to run extraction.",
  questions: [
    {
      id: "q-1",
      number: "1",
      text: "Which blood vessel carries blood away from the heart?",
      maxMarks: 2,
      marks: 2,
      status: "correct",
      answerText: "Arteries carry blood away from the heart.",
      regions: [{ page: 1, x: 7, y: 6, width: 86, height: 12, confidence: 0.99 }],
    },
    {
      id: "q-2",
      number: "2",
      text: "Which of the following organelles is primarily involved in photosynthesis?",
      maxMarks: 2,
      marks: 2,
      status: "correct",
      answerText: "The chloroplast is the organelle where photosynthesis mainly occurs.",
      feedback:
        "Excellent work! You correctly identified the chloroplast as the organelle responsible for photosynthesis. Keep it up!",
      regions: [{ page: 1, x: 6, y: 27, width: 88, height: 19, confidence: 0.98 }],
    },
    {
      id: "q-3",
      number: "3",
      text: "Explain the role of chloroplasts in photosynthesis, naming the main pigments involved and briefly outlining the two major stages of the process.",
      maxMarks: 2,
      marks: 2,
      status: "correct",
      answerText: "Chloroplasts contain chlorophyll. The light reaction captures light energy, while the dark reaction uses it to make glucose.",
      regions: [{ page: 1, x: 6, y: 49, width: 88, height: 16, confidence: 0.94 }],
    },
    {
      id: "q-4",
      number: "4",
      text: "Describe the flow of blood through the human heart starting from the right atrium and ending at the aorta; include the names of valves crossed.",
      maxMarks: 2,
      marks: 0,
      status: "unanswered",
      answerText: "No answer detected.",
      regions: [],
    },
    {
      id: "q-5",
      number: "5",
      text: "Draw a labelled diagram of an alveolus showing capillaries and air space (label alveolar sac, capillary, and direction of gas exchange).",
      maxMarks: 2,
      marks: 2,
      status: "correct",
      answerText: "A labelled alveolus diagram was detected.",
      regions: [{ page: 2, x: 6, y: 8, width: 88, height: 28, confidence: 0.9 }],
    },
    {
      id: "q-6",
      number: "6",
      text: "Draw a neat labelled diagram of the human digestive system (stomach, small intestine, large intestine, liver, pancreas) and label the organs.",
      maxMarks: 5,
      marks: 4,
      status: "partial",
      answerText: "The diagram is present. The pancreas label is unclear.",
      regions: [{ page: 2, x: 6, y: 41, width: 88, height: 32, confidence: 0.89 }],
    },
    {
      id: "q-7",
      number: "7",
      text: "Draw and label a nephron (Bowman's capsule, glomerulus, proximal tubule, loop of Henle, distal tubule, collecting duct).",
      maxMarks: 5,
      marks: 5,
      status: "correct",
      answerText: "All requested nephron structures were labelled.",
      regions: [{ page: 3, x: 6, y: 8, width: 88, height: 28, confidence: 0.93 }],
    },
    {
      id: "q-8",
      number: "8",
      text: "Explain the structural differences between palisade mesophyll and spongy mesophyll and state how each structure aids its function.",
      maxMarks: 5,
      marks: 3,
      status: "partial",
      answerText: "The answer describes cell arrangement but misses how air spaces support gas exchange.",
      regions: [{ page: 3, x: 6, y: 42, width: 88, height: 19, confidence: 0.92 }],
    },
    {
      id: "q-9",
      number: "9",
      text: "Describe the process of transpiration in plants in two to three sentences and name two environmental factors that increase its rate.",
      maxMarks: 5,
      marks: 5,
      status: "correct",
      answerText: "Water vapour exits through stomata. Higher temperature and wind speed increase the rate.",
      regions: [{ page: 3, x: 6, y: 67, width: 88, height: 21, confidence: 0.94 }],
    },
    {
      id: "q-10",
      number: "10",
      text: "Explain how the structure of xylem vessels facilitates water transport in plants (mention one structural feature and its role).",
      maxMarks: 5,
      marks: 4,
      status: "partial",
      answerText: "The answer mentions lignified walls but does not explain the continuous hollow tube.",
      regions: [{ page: 4, x: 6, y: 7, width: 88, height: 17, confidence: 0.91 }],
    },
    {
      id: "q-11a",
      number: "11a",
      text: "A diagram shows two potted plants – Plant A in bright light with broad green leaves, Plant B kept in dim light with pale, elongated leaves.",
      maxMarks: 2,
      marks: 2,
      status: "correct",
      answerText: "The diagram comparison is complete and correctly interpreted.",
      regions: [{ page: 4, x: 6, y: 29, width: 88, height: 18, confidence: 0.92 }],
    },
    {
      id: "q-11b",
      number: "11b",
      text: "Suggest one practical measure to help Plant B recover.",
      maxMarks: 3,
      marks: 1,
      status: "partial",
      answerText: "Move Plant B to brighter indirect light; one supporting reason is missing.",
      regions: [{ page: 4, x: 6, y: 51, width: 88, height: 12, confidence: 0.87 }],
    },
    {
      id: "q-12",
      number: "12",
      text: "A resting person has tidal volume (air per breath) of 0.5 L and breathes 12 times per minute.",
      maxMarks: 5,
      marks: 4,
      status: "partial",
      answerText: "Minute ventilation is calculated as 0.5 × 12 = 6 L/min; the unit is written once.",
      regions: [{ page: 4, x: 6, y: 66, width: 88, height: 13, confidence: 0.96 }],
    },
    {
      id: "q-13",
      number: "13",
      text: "If dead space is 0.15 L per breath, calculate the alveolar ventilation per minute. Show your working.",
      maxMarks: 5,
      marks: 4,
      status: "partial",
      answerText: "(0.5 − 0.15) × 12 = 4.2 L/min. The formula is correct; working is lightly annotated.",
      regions: [{ page: 4, x: 6, y: 83, width: 88, height: 12, confidence: 0.95 }],
    },
  ],
  unmatchedAnswers: [
    {
      id: "unmatched-1",
      label: "Unmatched note",
      page: 2,
      text: "A short diagram annotation could not be tied to a printed question.",
      x: 63,
      y: 78,
      width: 29,
      height: 9,
    },
  ],
};
